# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mitch-McK
email: mtmckinnon10@gmail.com
description: >
  This is the personal site for Mitch-McK. Take a look over any of my 
  current projects or articles as I post them here. I'm always open to 
  feedback and ideas, so don't be a stranger!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mitchellmckinnon.com" # the base hostname & protocol for your site
twitter_username: Mitch_McK
github_username: Mitch-McK

# Build settings
markdown: kramdown
