# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mitchell McKinnon
email: mtmckinnon10@gmail.com
description: Mitchell McKinnon's Homepage

logo: assets/img/logo.jpeg
google_analytics: G-744QEWNGV0

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mitchellmckinnon.com" # the base hostname & protocol for your site
twitter_username: Mitch_McK
github_username: Mitch-McK

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

test: "This is dynamiccccccc"
